/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.plan;

import org.apache.calcite.rel.RelNode;
import org.apache.calcite.rel.core.RelFactories;
import org.apache.calcite.tools.RelBuilderFactory;

import com.google.common.collect.ImmutableList;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.immutables.value.Value;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;
import java.util.function.Predicate;

/**
 * Rule that is parameterized via a configuration.
 * <p>Eventually (before Calcite version 2.0), this class will replace
 * {@link RelOptRule}. Constructors of {@code RelOptRule} are deprecated, so new
 * rule classes should extend {@code RelRule}, not {@code RelOptRule}.
 * Next, we will deprecate {@code RelOptRule}, so that variables that reference
 * rules will be of type {@code RelRule}.
 *
 * <p><b>Guidelines for writing rules</b>
 *
 * <p>1. If your rule is a sub-class of
 * {@link org.apache.calcite.rel.convert.ConverterRule}
 * and does not need any extra properties,
 * there's no need to create an {@code interface Config} inside your class.
 * In your class, create a constant
 * {@code public static final Config DEFAULT_CONFIG}. Goto step 5.
 *
 * <p>2. If your rule is not a sub-class of
 * {@link org.apache.calcite.rel.convert.ConverterRule},
 * create an inner {@code interface Config extends RelRule.Config} and
 * annotate it with {@code @Value.Immutable}. Note, if your inner class
 * is two levels deep (e.g. top-level Rule with Config inside), we recommend
 * you annotate the outer class with {@code @Value.Enclosing} which will
 * instruct the annotation processor to put your generated value class
 * inside a new Immutable outer class. If your rule is three levels deep,
 * the best thing to do is give your class a unique name to avoid any
 * generated code class name overlaps.
 * Implement {@link Config#toRule() toRule} using a {@code default} method:
 *
 * <blockquote>
 * <code>
 * &#x40;Override default CsvProjectTableScanRule toRule() {<br>
 * &nbsp;&nbsp;return new CsvProjectTableScanRule(this);<br>
 * }
 * </code>
 * </blockquote>
 *
 * <p>3. For each configuration property, create a pair of methods in your
 * {@code Config} interface. For example, for a property {@code foo} of type
 * {@code int}, create methods {@code foo} and {@code withFoo}:
 *
 * <blockquote><pre><code>
 * &#x2f;** Returns foo. *&#x2f;
 * int foo();
 *
 * &#x2f;** Sets {&#x40;link #foo}. *&#x2f;
 * Config withFoo(int x);
 * </code></pre></blockquote>
 *
 * <p>4. In your {@code Config} interface, create a {@code DEFAULT} constant
 * that represents the most typical configuration of your rule. This default
 * will leverage the Immutables class generated by the Annotation Processor
 * based on the annotation you provided above. For example,
 * {@code CsvProjectTableScanRule.Config} has the following:
 *
 * <blockquote><pre><code>
 * Config DEFAULT = ImmutableCsvProjectTableScanRule.Config.builder()
 *     .withOperandSupplier(b0 -&gt;
 *         b0.operand(LogicalProject.class).oneInput(b1 -&gt;
 *             b1.operand(CsvTableScan.class).noInputs()))
 *      .build();
 * </code></pre></blockquote>
 *
 * <p>5. Do not create an {@code INSTANCE} constant inside your rule.
 * Instead, create a named instance of your rule, with default configuration,
 * in a holder class. The holder class must not be a sub-class of
 * {@code RelOptRule} (otherwise cyclic class-loading issues may arise).
 * Generally it will be called <code><i>Xxx</i>Rules</code>, for example
 * {@code CsvRules}. The rule instance is named after your rule, and is based
 * on the default config ({@code Config.DEFAULT}, or {@code DEFAULT_CONFIG} for
 * converter rules):
 *
 * <blockquote><pre><code>
 * &#x2f;** Rule that matches a {&#x40;code Project} on a
 *  * {&#x40;code CsvTableScan} and pushes down projects if possible. *&#x2f;
 * public static final CsvProjectTableScanRule PROJECT_SCAN =
 *     CsvProjectTableScanRule.Config.DEFAULT.toRule();
 * </code></pre></blockquote>
 *
 * @param <C> Configuration type
 */
// RelRule 是 Apache Calcite 优化器框架中用于替代传统 RelOptRule 的现代化、参数化（Parameterized）规则基类。
// 传统的 RelOptRule 由于依赖大量且繁琐的构造方法重载、静态工厂方法（如 operand()、operandJ()）以及内部硬编码，导致规则定义臃肿、复用性差，并且难以进行灵活的属性微调。
// 为了解决这些痛点，Calcite 从 1.x 中后期引入了 RelRule，并在 2.0 时代将其完全确立为定义优化规则的核心底座。
// 核心作用
// 全面参数化与配置解耦（Configuration-Driven）：RelRule 将规则的拓扑匹配（Operand）和内部控制行为（如某些阈值或开关）统一抽离到内部 Config 接口中。规则子类不再通过构造函数死板地硬编码匹配逻辑，而是完全由外部注入的配置驱动。
// 拥抱类型安全的声明式流式 DSL（Domain Specific Language）：提供了由 OperandTransform、OperandBuilder 和 OperandDetailBuilder 组成的现代化流式接口。开发者可以通过清晰的链式调用，声明式地组装出极具语义感的算子树匹配模式。
// 消除编译期重载爆炸：淘汰了旧体系下各种参数交错的静态重载函数，将类型、特质、过滤谓词、子节点输入策略完全解耦到独立的流式组件方法中。
// 基于第三方注解的不可变配置生成：全面依托 @Value.Immutable 自动代码生成技术（编译期注解处理器），使规则配置天然具备线程安全、流式构建（Builder Pattern）的现代化特性。
// OperandTransform（定义变异转换）：这是一个顶层声明式接口（高阶函数），用来接收一个 Builder 并对它进行定制。
// OperandBuilder（构建起始站）：当你想为某个算子（比如 LogicalFilter）指定它的下层子节点（Inputs）匹配规则时，你处于这个阶段。
// OperandDetailBuilder（细节雕刻站）：当你想为当前算子指定自身细节特征（比如：谓词条件是什么、满足什么特征约束 Convention）时，你处于这个阶段。
// 它们在代码中的流式运转轨迹通常如下：
// // 以定义一个匹配 Filter 压入 Project 的规则为例：
// OperandTransform transform = b0 ->
//    b0.operand(LogicalFilter.class)          // 1. 进入 OperandBuilder 阶段
//      .predicate(f -> f.containsSubquery())  // 2. 升级为 OperandDetailBuilder 阶段，雕刻 Filter 自身细节
//      .oneInput(b1 ->                        // 3. 再次切回 OperandBuilder 阶段，去定义它的下层子节点输入
//          b1.operand(LogicalProject.class).anyInputs()
//      );
public abstract class RelRule<C extends RelRule.Config> extends RelOptRule {
  // 当前规则实例持有的只读/不可变配置对象。
  // 它包含了该规则运行所需的一切元数据（包括操作数生成器、算子工厂、唯一描述信息以及子类自定义的各种微调参数）。
  public final C config;

  /** Creates a RelRule. */
  protected RelRule(C config) {
    super(OperandBuilderImpl.operand(config.operandSupplier()), //这里通过config.operandSupplier()函数 提供的OperandTransform就可以构建RelOptRuleOperand
        config.relBuilderFactory(), config.description());
    this.config = config;
  }

  /** Rule configuration. */
  public interface Config {
    //主要方法toRule()、operandSupplier()和withOperandSupplier(OperandTransform transform)

    /** Creates a rule that uses this configuration. Sub-class must override. */
    // 配置转化为规则对象的生命周期终点方法
    // 子类必须以 default 方法实现此接口。当外部将一个 Config 对象的各项参数通过 Builder 调整完毕后，
    // 调用 toRule() 就会执行 new MyRule(this)，将当前的配置固化封装为一个真正的、可提交给优化器的规则实例。
    RelOptRule toRule();

    /** Casts this configuration to another type, usually a sub-class. */
    // 提供便捷的安全类型转换（Downcasting）工具。
    default <T extends Object> T as(Class<T> class_) {
      if (class_.isAssignableFrom(this.getClass())) { //说明class_是this的父类
        return class_.cast(this); //把this转为class_类型，父类可以转为子类
      } else {
        throw new UnsupportedOperationException(
            String.format(Locale.ROOT,
                "The current config of type %s is not an instance of %s.",
                this.getClass(),
                class_));
      }
    }

    /** The factory that is used to create a
     * {@link org.apache.calcite.tools.RelBuilder} during rule invocations. */
    // 定义当前规则专用的关系代数构建工厂。
    @Value.Default default RelBuilderFactory relBuilderFactory() {
      return RelFactories.LOGICAL_BUILDER;
    }

    /** Sets {@link #relBuilderFactory()}. */
    Config withRelBuilderFactory(RelBuilderFactory factory);

    /** Description of the rule instance. */
    // CALCITE-4831: remove the second nullable annotation once immutables/#1261 is fixed
    @javax.annotation.Nullable @Nullable String description();

    /** Sets {@link #description()}. */
    Config withDescription(@Nullable String description);

    /** Creates the operands for the rule instance.
     * OperandTransform是一个函数接口，接收OperandBuilder参数，返回Done*/
    // 获取定义此规则匹配拓扑的操作数转换闭包（供应器）
    @Value.Default default OperandTransform operandSupplier() {
      return s -> {
        throw new IllegalArgumentException("Rules must have at least one "
            + "operand. Call Config.withOperandSupplier to specify them.");
      };

    }

    /** Sets {@link #operandSupplier()}. */
    Config withOperandSupplier(OperandTransform transform);
  }

  /** Function that creates an operand.
   *
   * @see Config#withOperandSupplier(OperandTransform) */
  // 操作数拓扑转换的核心闭包函数式接口。
  // 它接收一个白纸一张的 OperandBuilder 绘图板，在 Lambda 内部对这块板执行一系列的操作数属性绘制，最终返回一个表示画作落笔的 Done 标记令牌。
  @FunctionalInterface
  public interface OperandTransform extends Function<OperandBuilder, Done> {
  }

  /** Callback to create an operand.
   *
   * @see OperandTransform */
  // 拓扑引导者接口
  public interface OperandBuilder {
    /** Starts building an operand by specifying its class.
     * Call further methods on the returned {@link OperandDetailBuilder} to
     * complete the operand.
     * */
    // 开始构建一个操作数，指定此操作数需要匹配的RelNode类型。relClass是一个Class对象，表示操作数所要匹配的关系表达式节点的类型
    // 返回一个OperandDetailBuilder对象，用于进一步为该操作数设置细节，如输入模式、转换特性等
    // 开启一个标准操作数的构建流程，指定要拦截的目标关系代数节点类型（relClass）。返回明细构建器，用来做进一步属性填充。
    <R extends RelNode> OperandDetailBuilder<R> operand(Class<R> relClass);

    /** Supplies an operand that has been built manually.
     * */
    // 旧版规则兼容型安全接口。允许开发者直接把一个已经在外部手工 new 好的传统 RelOptRuleOperand 拍到当前 Builder 中，无缝绕过流式体系，并立刻返回完成标记 Done。
    // 直接指定一个已经手动构建的操作数。即允许用户直接传入已经构建好的操作数而不是通过OperandBuilder一步步生成
    Done exactly(RelOptRuleOperand operand);
  }

  /** Indicates that an operand is complete.
   *
   * @see OperandTransform */
  // 纯粹的编译期防断言/防漏写标记型接口。
  public interface Done {
  }

  /** Add details about an operand, such as its inputs.
   *
   * @param <R> Type of relational expression */
  public interface OperandDetailBuilder<R extends RelNode> {
    /** Sets a trait of this operand. 设置特性*/
    OperandDetailBuilder<R> trait(RelTrait trait);

    /** Sets the predicate of this operand. 设置谓词*/
    OperandDetailBuilder<R> predicate(Predicate<? super R> predicate);

    /** Indicates that this operand has a single input. */
    Done oneInput(OperandTransform transform);

    /** Indicates that this operand has several inputs. */
    Done inputs(OperandTransform... transforms);

    /** Indicates that this operand has several inputs, unordered. */
    Done unorderedInputs(OperandTransform... transforms);

    /** Indicates that this operand takes any number or type of inputs. */
    Done anyInputs();

    /** Indicates that this operand takes no inputs. */
    Done noInputs();

    /** Indicates that this operand converts a relational expression to
     * another trait. */
    Done convert(RelTrait in);
  }

  /** Implementation of {@link OperandBuilder}. */
  private static class OperandBuilderImpl implements OperandBuilder {
    final List<RelOptRuleOperand> operands = new ArrayList<>();

    /**
     *为什么 operands.size() == 1 是必要的？
     * 单一操作数的构建：在调用 operand(OperandTransform transform) 方法时，期望的行为是只构建一个操作数。
     * OperandTransform 被设计用来构建 单个 操作数，这也是调用链中 OperandBuilder 的职责。
     *
     * 确保规范性：通过检查 operands.size() == 1，该方法确保每次调用只会生成一个有效的操作数，避免用户错误地构建了多个操作数，或者没有构建任何操作数。
     * 如果不进行这样的检查，可能会导致规则匹配时的逻辑混乱。
     *
     * 操作数的明确性：RelOptRuleOperand 表示一个关系表达式匹配规则，它本质上是一个模式。因此，在一个 RelRule 中，一个操作数对应一个具体的匹配模式。
     * 如果多个操作数混杂在一起，规则的定义就会变得模糊不清。
     *
     * 总结：
     * operand(OperandTransform transform) 方法之所以要求 operands.size() == 1，是为了确保每次调用该方法时只构建了一个 RelOptRuleOperand，
     * 即每次规则定义时只构建一个匹配模式。
     * 这个检查是为了保证代码的规范性和正确性，避免错误操作。
     */
    static RelOptRuleOperand operand(OperandTransform transform) {
      final OperandBuilderImpl b = new OperandBuilderImpl();
      final Done done = transform.apply(b);
      Objects.requireNonNull(done, "done");
      if (b.operands.size() != 1) {
        throw new IllegalArgumentException("operand supplier must call one of "
            + "the following methods: operand or exactly");
      }
      return b.operands.get(0);
    }

    @Override public <R extends RelNode> OperandDetailBuilder<R> operand(Class<R> relClass) {
      //这里的parent传入OperandBuilder本身，是为了让Detail更好操作operands属性，构建RelOptRuleOperand
      return new OperandDetailBuilderImpl<>(this, relClass);
    }

    @Override public Done exactly(RelOptRuleOperand operand) {
      operands.add(operand);
      return DoneImpl.INSTANCE;
    }
  }

  /** Implementation of {@link OperandDetailBuilder}.
   *
   * @param <R> Type of relational expression */
  private static class OperandDetailBuilderImpl<R extends RelNode>
      implements OperandDetailBuilder<R> {
    private final OperandBuilderImpl parent;
    //指定要构建的操作数的具体类型，确保其符合预期的关系表达式类型
    private final Class<R> relClass;
    // 用于构建该操作数的输入，支持复杂的关系表达式结构
    final OperandBuilderImpl inputBuilder = new OperandBuilderImpl();
    private @Nullable RelTrait trait;
    private Predicate<? super R> predicate = r -> true;

    OperandDetailBuilderImpl(OperandBuilderImpl parent, Class<R> relClass) {
      this.parent = Objects.requireNonNull(parent, "parent");
      this.relClass = Objects.requireNonNull(relClass, "relClass");
    }

    @Override public OperandDetailBuilderImpl<R> trait(RelTrait trait) {
      this.trait = Objects.requireNonNull(trait, "trait");
      return this;
    }

    @Override public OperandDetailBuilderImpl<R> predicate(Predicate<? super R> predicate) {
      this.predicate = predicate;
      return this;
    }

    /** Indicates that there are no more inputs. */
    Done done(RelOptRuleOperandChildPolicy childPolicy) {
      parent.operands.add(
          new RelOptRuleOperand(relClass, trait, predicate, childPolicy,
              ImmutableList.copyOf(inputBuilder.operands)));
      return DoneImpl.INSTANCE;
    }

    @Override public Done convert(RelTrait in) {
      parent.operands.add(
          new ConverterRelOptRuleOperand(relClass, in, predicate));
      return DoneImpl.INSTANCE;
    }

    @Override public Done noInputs() {
      return done(RelOptRuleOperandChildPolicy.LEAF);
    }

    @Override public Done anyInputs() {
      return done(RelOptRuleOperandChildPolicy.ANY);
    }

    @Override public Done oneInput(OperandTransform transform) {
      final Done done = transform.apply(inputBuilder);
      Objects.requireNonNull(done, "done");
      return done(RelOptRuleOperandChildPolicy.SOME);
    }

    @Override public Done inputs(OperandTransform... transforms) {
      for (OperandTransform transform : transforms) {
        final Done done = transform.apply(inputBuilder);
        Objects.requireNonNull(done, "done");
      }
      return done(RelOptRuleOperandChildPolicy.SOME);
    }

    @Override public Done unorderedInputs(OperandTransform... transforms) {
      for (OperandTransform transform : transforms) {
        final Done done = transform.apply(inputBuilder);
        Objects.requireNonNull(done, "done");
      }
      return done(RelOptRuleOperandChildPolicy.UNORDERED);
    }
  }

  /** Singleton instance of {@link Done}.
   * DoneImpl.INSTANCE 是一个枚举常量，它在类加载时就被创建，并且只会创建一次，确保它是唯一的实例。
   * 由于 DoneImpl 实现了 Done 接口，INSTANCE 常量可以作为 Done 类型的实例在代码中传递，用于表示操作数的构建完成。
   * */
  private enum DoneImpl implements Done {
    INSTANCE
  }

  /** Callback interface that helps you avoid creating sub-classes of
   * {@link RelRule} that differ only in implementations of
   * {@link #onMatch(RelOptRuleCall)} method.
   *
   * @param <R> Rule type
   *
   * MatchHandler 类的作用
   * 回调接口:
   *
   * MatchHandler 是一个函数式接口，继承自 BiConsumer<R, RelOptRuleCall>。这意味着它具有一个接受两个参数的 accept 方法，分别是规则的实例和规则调用的上下文。其主要目的是作为处理匹配的回调函数。
   * 简化规则匹配的实现:
   *
   * 在实现 RelRule 的子类时，通常需要重写 onMatch(RelOptRuleCall call) 方法，以定义在匹配规则时要执行的操作。使用 MatchHandler 接口，开发者可以将匹配逻辑封装在 MatchHandler 的实现中，而不需要在每个规则中重复编写 onMatch 的实现。这有助于提高代码的可重用性和可维护性。
   * 类型安全:
   *
   * MatchHandler<R extends RelOptRule> 中的类型参数 R 使得开发者可以创建特定于某种规则的处理程序。这样，开发者可以将具体的规则类传递给处理程序，确保类型安全。
   * 灵活性:
   *
   * 由于它是一个函数式接口，MatchHandler 可以使用 Lambda 表达式或方法引用来实现，从而提供了更灵活和简洁的代码编写方式。
   *
   *
   * public class MyJoinRule extends RelRule<MyJoinRule.Config> {
   *
   *   // 使用 MatchHandler 来定义 onMatch 的逻辑
   *   private static final MatchHandler<MyJoinRule> HANDLER = (rule, call) -> {
   *     // 这里可以添加逻辑处理匹配到的规则
   *   };
   *
   *   // 在构造函数或其他地方使用 HANDLER
   *   @Override
   *   public void onMatch(RelOptRuleCall call) {
   *     HANDLER.accept(this, call);
   *   }
   * }
   * */
  public interface MatchHandler<R extends RelOptRule>
      extends BiConsumer<R, RelOptRuleCall> {
  }
}
