@startuml
'https://plantuml.com/class-diagram

interface Metadata {
  RelNode rel()
}

interface  MetadataHandler{
MetadataDef<M> getDef()
static SortedMap<String, Method> handlerMethods(Class<? extends MetadataHandler<?>> handlerClass)
}

class MetadataDef<M extends Metadata> {
Class<M> metadataClass
Class<? extends MetadataHandler<M>> handlerClass
ImmutableList<Method> methods

}

note right of MetadataDef :为什么要传入methods，并且要校验数量跟handlerClass相等，并且参数比handlerClass的少两参数


Metadata *-- MetadataDef
MetadataHandler *-- MetadataDef

interface MetadataHandlerProvider {
<MH extends MetadataHandler<?>> MH handler(Class<MH> handlerClass)
default <MH extends MetadataHandler<?>> MH revise(Class<MH> handlerClass)
}

interface RelMetadataProvider{
<@Nullable M extends @Nullable Metadata> @Nullable UnboundMetadata<M> apply(Class<? extends RelNode> relClass, Class<? extends M> metadataClass)
<M extends Metadata> Multimap<Method, MetadataHandler<M>> handlers(MetadataDef<M> def)
List<MetadataHandler<?>> handlers(Class<? extends MetadataHandler<?>> handlerClass)
}

@enduml
