/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.plan.volcano;

import org.apache.calcite.plan.RelHintsPropagator;
import org.apache.calcite.plan.RelOptListener;
import org.apache.calcite.plan.RelOptRuleCall;
import org.apache.calcite.plan.RelOptRuleOperand;
import org.apache.calcite.plan.RelOptRuleOperandChildPolicy;
import org.apache.calcite.rel.PhysicalNode;
import org.apache.calcite.rel.RelNode;
import org.apache.calcite.rel.rules.SubstitutionRule;
import org.apache.calcite.rel.rules.TransformationRule;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Lists;

import org.checkerframework.checker.nullness.qual.Nullable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import static org.apache.calcite.linq4j.Nullness.castNonNull;

import static java.util.Objects.requireNonNull;

/**
 * <code>VolcanoRuleCall</code> implements the {@link RelOptRuleCall} interface
 * for VolcanoPlanner.
 */
// VolcanoRuleCall 是 Apache Calcite 项目中服务于 VolcanoPlanner（基于代价的动态规划优化器） 的具体规则调用实现。
// VolcanoRuleCall 要复杂得多。因为它需要将新生成的算子树优雅地整合进 Volcano 核心的等价图（Memo 备忘录）结构中，并且要在线处理极其复杂的双向拓扑匹配与回溯算法。
// 主要承担以下两个核心职责：
// 多维度的双向拓扑匹配引擎（Match Engine）：
//Volcano 优化器允许规则的匹配顺序不是死板的“自上而下”。通过内部的 solveOrder（解题顺序），匹配可以在算子树中逆流而上（从子节点找父节点，即递增模式）或顺流而下（从父节点找子节点，即递减模式）。VolcanoRuleCall 的主要工作就是利用深度优先搜索（DFS）和回溯法，在复杂的等价类（RelSubset）之间游走，把所有能够拼装成目标模式的算子组合一个不漏地全挖掘出来。
// Memo（等价群组）的高效注册桥梁：
//当规则转换成功并调用 transformTo 时，它不仅要确保新算子 rel 的合法性，更重要的任务是调用 volcanoPlanner.ensureRegistered 将新算子绑定到原本老算子所属的 RelSet / RelSubset 中。这种“同台竞技”的注册方式，开辟了平行的搜索空间，使得 Volcano 优化器在最后阶段能够使用动态规划算法挑选出代价最低的完美物理执行计划。
public class VolcanoRuleCall extends RelOptRuleCall {
  //~ Instance fields --------------------------------------------------------
  // 强类型指向当前的 Volcano 优化器。
  // 方便在运行时直接调用优化器的核心方法，如节点注册（ensureRegistered）、修剪（prune）等。
  protected final VolcanoPlanner volcanoPlanner;

  /**
   * List of {@link RelNode} generated by this call. For debugging purposes.
   */
  // 调试追踪容器。当处于 Debug 日志级别时，用来临时存储当前这次规则触发所产出的所有新算子，以便在日志中集中打印 call#X generated Y successors。
  private @Nullable List<RelNode> generatedRelList;

  //~ Constructors -----------------------------------------------------------

  /**
   * Creates a rule call, internal, with array to hold bindings.
   *
   * @param planner Planner
   * @param operand First operand of the rule
   * @param rels    Array which will hold the matched relational expressions
   * @param nodeInputs For each node which matched with {@code matchAnyChildren}
   *                   = true, a list of the node's inputs
   */
  protected VolcanoRuleCall(
      VolcanoPlanner planner,
      RelOptRuleOperand operand,
      RelNode[] rels,
      Map<RelNode, List<RelNode>> nodeInputs) {
    super(planner, operand, rels, nodeInputs);
    this.volcanoPlanner = planner;
  }

  /**
   * Creates a rule call.
   *
   * @param planner Planner
   * @param operand First operand of the rule
   */
  VolcanoRuleCall(
      VolcanoPlanner planner,
      RelOptRuleOperand operand) {
    this(
        planner,
        operand,
        new RelNode[operand.getRule().operands.size()],
        ImmutableMap.of());
  }

  //~ Methods ----------------------------------------------------------------
  // 在 Volcano 优化器中，由于采用了基于 Memo（备忘录） 机制的动态规划算法，生成新算子时绝对不能简单地就地替换老算子，而是要将其织入到庞大的等价网络中，让新老算子“同台竞技”。
  // Calcite 的优化规则分为两大家族：
  // TransformationRule（转换规则）：负责逻辑层改写（如 Filter 下推、Join 颠倒顺序）。它期望输入和产出的都是逻辑算子。
  // ConverterRule / ImplementationRule（转换/实现规则）：负责将逻辑算子物理化（如 LogicalJoin $\rightarrow$ EnumerableHashJoin）。
  @Override public void transformTo(RelNode rel, Map<RelNode, RelNode> equiv,
      RelHintsPropagator handler) {
    // 拦截非法跨界：逻辑与物理的“柏林墙”
    // 如果一个声明为 TransformationRule 的逻辑规则，在执行完后竟然越权产生了一个物理节点（PhysicalNode），这会导致 Volcano 优化器的优化阶段（Phase）发生严重混乱。
    // 此处抛出运行时异常，是框架在编译/运行期立起的一道安全防御哨卡。
    if (rel instanceof PhysicalNode
        && rule instanceof TransformationRule) {
      throw new RuntimeException(
          rel + " is a PhysicalNode, which is not allowed in " + rule);
    }
    // Hint 传播与 Debug 追踪
    // 根节点 rels[0] 身上的 SQL Hint 提示在此处通过传递进来的 handler 被精准拷贝给新根 rel。同时，如果全局开启了 Debug 日志，会将这个新诞生的算子塞进 generatedRelList 中。
    // 正如我们在前一章提到的，这完全是为了在规则跑完后在日志里集中打印类似 call#10 generated 3 successors 的追踪线索。
    rel = handler.propagate(rels[0], rel);
    if (LOGGER.isDebugEnabled()) {
      LOGGER.debug("Transform to: rel#{} via {}{}", rel.getId(), getRule(),
          equiv.isEmpty() ? "" : " with equivalences " + equiv);
      if (generatedRelList != null) {
        generatedRelList.add(rel);
      }
    }
    try {
      // It's possible that rel is a subset or is already registered.
      // Is there still a point in continuing? Yes, because we might
      // discover that two sets of expressions are actually equivalent.
      // 事件通知：VolcanoPlanner 允许注册外部监听器（Listener），此处传入 true 代表“新算子的生成流程正式开始”，通知外部进行指标统计或性能监控。
      if (volcanoPlanner.getListener() != null) {
        RelOptListener.RuleProductionEvent event =
            new RelOptListener.RuleProductionEvent(
                volcanoPlanner,
                rel,
                this,
                true);
        volcanoPlanner.getListener().ruleProductionSucceeded(event);
      }
      //如果当前应用的规则是 SubstitutionRule 类型，并且规则设置了 autoPruneOld() 为 true，则表示在应用规则时，应该自动修剪旧的关系节点。调用 volcanoPlanner.prune(rels[0]) 来删除当前的旧节点。
      if (this.getRule() instanceof SubstitutionRule
          && ((SubstitutionRule) getRule()).autoPruneOld()) {
        volcanoPlanner.prune(rels[0]);
      }
      //这段代码遍历 equiv 映射中的每个条目，注册等价的关系节点。
      // volcanoPlanner.ensureRegistered 会确保这些节点被注册到 Volcano 规划器中，以便它们参与后续的优化过程
      // Registering the root relational expression implicitly registers
      // its descendants. Register any explicit equivalences first, so we
      // don't register twice and cause churn.
      // 局部等价映射的优先注册
      // 如果在 onMatch 内部，规则不仅改写了树根，还顺手改写了新树内部的某个子节点（例如把内部的 LogicalProject A 改写成了 LogicalProject B），并存在 equiv 映射表里，优化器要求必须优先注册这些内部的局部等价对。
      for (Map.Entry<RelNode, RelNode> entry : equiv.entrySet()) {
        volcanoPlanner.ensureRegistered(
            entry.getKey(), entry.getValue());
      }
      //这一步确保新的关系节点 rel 被注册到 Volcano 规划器中，并将其与原始关系节点 rels[0] 进行关联。
      // RelSubset 用于表示一个关系节点的子集，但在此代码中，它仅用于调试目的
      // The subset is not used, but we need it, just for debugging
      @SuppressWarnings("unused")
      // 请把新算子 rel 强行塞进老算子 rels[0] 当前所属的那个等价集合（RelSet）和子集（RelSubset）中。
      RelSubset subset = volcanoPlanner.ensureRegistered(rel, rels[0]);

      if (volcanoPlanner.getListener() != null) {
        RelOptListener.RuleProductionEvent event =
            new RelOptListener.RuleProductionEvent(
                volcanoPlanner,
                rel,
                this,
                false);
        volcanoPlanner.getListener().ruleProductionSucceeded(event);
      }
    } catch (Exception e) {
      throw new RuntimeException("Error occurred while applying rule "
          + getRule(), e);
    }
  }

  /**
   * Called when all operands have matched.
   */
  // 当拓扑匹配算法（matchRecurse）完成了所有繁重的多叉树对齐、回溯搜索，确认找到了能够触发某条规则的一组算子（rels）后，并不会盲目地直接执行。
  // 它会把这组算子送交到 onMatch() 方法中，进行极其严苛的 5 道火线安全盘查。
  protected void onMatch() {
    assert getRule().matches(this); //确保当前规则（getRule()）确实与当前的 VolcanoRuleCall 对象匹配
    volcanoPlanner.checkCancel(); //检查是否有外部取消信号的函数，如果当前操作被取消了（例如，由于时间超限），则后续的规则应用将停止
    try {
      // 第 1 道卡点：全局拉黑（volcanoPlanner.isRuleExcluded）
      // 检查这条规则是否在整个 Planner 级别被全局拉黑（例如通过优化器配置显式禁用了某些特定规则）。
      if (volcanoPlanner.isRuleExcluded(getRule())) {
        LOGGER.debug("Rule [{}] not fired due to exclusion filter", getRule());
        return;
      }
      // 第 2 道卡点：Hint 局部拉黑（isRuleExcluded()）
      // 盘查本次匹配到的这组算子中，是否有任何一个节点的 SQL Hint 宣告了对本规则的封杀。
      if (isRuleExcluded()) {
        LOGGER.debug("Rule [{}] not fired due to exclusion hint", getRule());
        return;
      }
      // 第 3 道卡点：等价类游离检查（subset == null）
      for (int i = 0; i < rels.length; i++) {
        RelNode rel = rels[i];
        RelSubset subset = volcanoPlanner.getSubset(rel);
        // 在 Volcano 中，每个有效的算子都必须归属于一个 Memo 等价子集（RelSubset）。
        // 如果发现某个匹配到的算子在 Memo 结构中居然找不到对应的 subset，说明它是一个游离的、“无家可归”的无效节点，直接熔断。
        if (subset == null) {
          LOGGER.debug(
              "Rule [{}] not fired because operand #{} ({}) has no subset",
              getRule(), i, rel);
          return;
        }
        // 第 4 道卡点：过时与死枝拦截（equivalentSet != null 或不包含）
        // 这是高并发优化中最关键的拦截。因为 Volcano 是多规则并发、交错触发的。
        // 在你这条规则在队列里排队等待触发的期间，别的规则可能刚刚把你的某个操作数所在的 RelSet 给合并（Merge）到了另一个更大的集合里（导致 equivalentSet != null），
        // 或者由于算子重命名等原因，该算子已经被踢出了原本的子集。此时，这个算子被称为 Obsolete（过时的）。如果在过时的“死枝”上继续做变换，纯粹是白白浪费 CPU 算力。
        if ((subset.set.equivalentSet != null)
            // When rename RelNode via VolcanoPlanner#rename(RelNode rel),
            // we may remove rel from its subset: "subset.set.rels.remove(rel)".
            // Skip rule match when the rel has been removed from set.
            || (subset != rel && !subset.contains(rel))) { //如果子集的等价集不为空，或者子集不包含当前节点，则认为该操作数已经过时或不再有效，跳过该规则
          LOGGER.debug(
              "Rule [{}] not fired because operand #{} ({}) belongs to obsolete set",
              getRule(), i, rel);
          return;
        }
        // 第 5 道卡点：剪枝拦截（prunedNodes.contains(rel)）
        // 如果某个算子节点被其他规则或优化器标记为了“已剪枝”（其 Importance 重要性被置为了 0，意味着它已经彻底失去了成为最佳计划的可能），那么基于它进行的再次衍生也毫无意义，直接无情拒绝。
        if (volcanoPlanner.prunedNodes.contains(rel)) {
          LOGGER.debug("Rule [{}] not fired because operand #{} ({}) has importance=0",
              getRule(), i, rel);
          return;
        }
      }

      if (volcanoPlanner.getListener() != null) {
        RelOptListener.RuleAttemptedEvent event =
            new RelOptListener.RuleAttemptedEvent(
                volcanoPlanner,
                rels[0],
                this,
                true);
        volcanoPlanner.getListener().ruleAttempted(event);
      }

      if (LOGGER.isDebugEnabled()) {
        this.generatedRelList = new ArrayList<>();
      }
      // 阶段二：栈上下文管理与核心执行
      // 1. 将当前的规则调用（Call）推入火山优化器的执行栈顶
      volcanoPlanner.ruleCallStack.push(this);
      try {
        // 2. 真正唤醒、并交出控制权给开发者写的转换业务逻辑
        getRule().onMatch(this);
      } finally {
        volcanoPlanner.ruleCallStack.pop();
      }
      // 阶段三：事件通知与调试日志收尾
      if (generatedRelList != null) {
        if (generatedRelList.isEmpty()) {
          LOGGER.debug("call#{} generated 0 successors.", id);
        } else {
          LOGGER.debug(
              "call#{} generated {} successors: {}",
              id, generatedRelList.size(), generatedRelList);
        }
        this.generatedRelList = null;
      }

      if (volcanoPlanner.getListener() != null) {
        RelOptListener.RuleAttemptedEvent event =
            new RelOptListener.RuleAttemptedEvent(
                volcanoPlanner,
                rels[0],
                this,
                false);
        volcanoPlanner.getListener().ruleAttempted(event);
      }
    } catch (Exception e) {
      throw new RuntimeException("Error while applying rule " + getRule()
          + ", args " + Arrays.toString(rels), e);
    }
  }

  /**
   * Applies this rule, with a given relational expression in the first slot.
   */
  void match(RelNode rel) {
    assert getOperand0().matches(rel) : "precondition";
    final int solve = 0;
    int operandOrdinal = castNonNull(getOperand0().solveOrder)[solve];
    this.rels[operandOrdinal] = rel;
    matchRecurse(solve + 1);
  }

  /**
   * Recursively matches operands above a given solve order.
   *
   * @param solve Solve order of operand (&gt; 0 and &le; the operand count)
   */
  private void matchRecurse(int solve) {
    assert solve > 0;  //两个断言确保 solve 的值在合法范围内。solve 表示当前正在匹配的操作数的索引，必须大于 0 且小于等于规则操作数的数量
    assert solve <= rule.operands.size();
    final List<RelOptRuleOperand> operands = getRule().operands;
    if (solve == operands.size()) { //当 solve 达到操作数的数量时，表示所有的操作数都已经被匹配。
      // 此时，调用规则的 matches 方法来检查规则的副条件（side-conditions）是否满足。如果满足，则调用 onMatch() 应用规则
      // We have matched all operands. Now ask the rule whether it
      // matches; this gives the rule chance to apply side-conditions.
      // If the side-conditions are satisfied, we have a match.
      if (getRule().matches(this)) {
        onMatch();
      }
    } else {
      //solveOrder 数组存储了操作数匹配的顺序。operandOrdinal 和 previousOperandOrdinal 分别表示当前和前一个操作数的顺序。
      // 如果当前操作数的顺序小于前一个操作数，则设置 ascending 为 true，表示我们是在逐步递增地匹配操作数，否则就是递减匹配
      final int[] solveOrder = castNonNull(operand0.solveOrder);
      final int operandOrdinal = solveOrder[solve];
      final int previousOperandOrdinal = solveOrder[solve - 1];
      boolean ascending = operandOrdinal < previousOperandOrdinal;
      final RelOptRuleOperand previousOperand =
          operands.get(previousOperandOrdinal);  //前一个操作数
      final RelOptRuleOperand operand = operands.get(operandOrdinal); //当前操作数
      final RelNode previous = rels[previousOperandOrdinal]; //前一个短息节点

      final RelOptRuleOperand parentOperand;
      final Collection<? extends RelNode> successors;
      if (ascending) {
        //如果是递增模式（ascending），表示当前操作数是前一个操作数的子节点。
        // getSubsetNonNull(previous) 获取前一个操作数的子集（RelSubset），
        // 然后获取该子集的所有父关系节点作为后继节点。
        assert previousOperand.getParent() == operand;
        assert operand.getMatchedClass() != RelSubset.class;
        if (previousOperand.getMatchedClass() != RelSubset.class
            && previous instanceof RelSubset) {
          throw new RuntimeException("RelSubset should not match with "
              + previousOperand.getMatchedClass().getSimpleName());
        }
        parentOperand = operand;
        final RelSubset subset = volcanoPlanner.getSubsetNonNull(previous);
        successors = subset.getParentRels();
      } else {
        //如果不是递增模式，表示当前操作数是前一个操作数的父节点。在这种情况下，需要获取当前操作数的父操作数，并从父节点的输入列表中获取后继节点
        parentOperand =
            requireNonNull(operand.getParent(),
                () -> "operand.getParent() for " + operand);
        final RelNode parentRel = rels[parentOperand.ordinalInRule];
        final List<RelNode> inputs = parentRel.getInputs();
        // if the child is unordered, then add all rels in all input subsets to the successors list
        // because unordered can match child in any ordinal
        if (parentOperand.childPolicy == RelOptRuleOperandChildPolicy.UNORDERED) {
          if (operand.getMatchedClass() == RelSubset.class) {
            // Find all the sibling subsets that satisfy this subset's traitSet
            successors = inputs.stream()
              .flatMap(subset -> ((RelSubset) subset).getSubsetsSatisfyingThis())
              .collect(Collectors.toList());
          } else {
            List<RelNode> allRelsInAllSubsets = new ArrayList<>();
            Set<RelNode> duplicates = new HashSet<>();
            for (RelNode input : inputs) {
              if (!duplicates.add(input)) {
                // Ignore duplicate subsets
                continue;
              }
              RelSubset inputSubset = (RelSubset) input;
              for (RelNode rel : inputSubset.getRels()) {
                if (!duplicates.add(rel)) {
                  // Ignore duplicate relations
                  continue;
                }
                allRelsInAllSubsets.add(rel);
              }
            }
            successors = allRelsInAllSubsets;
          }
        } else if (operand.ordinalInParent < inputs.size()) {
          // child policy is not unordered
          // we need to find the exact input node based on child operand's ordinalInParent
          final RelSubset subset =
              (RelSubset) inputs.get(operand.ordinalInParent);
          if (operand.getMatchedClass() == RelSubset.class) {
            // Find all the sibling subsets that satisfy this subset'straitSet
            successors =
              subset.getSubsetsSatisfyingThis().collect(Collectors.toList());
          } else {
            successors = subset.getRelList();
          }
        } else {
          // The operand expects parentRel to have a certain number
          // of inputs and it does not.
          successors = ImmutableList.of();
        }
      }

      for (RelNode rel : successors) {
        //如果 TransformationRule 规则并且后继节点的 convention 与前一个节点不同，跳过该节点
        if (operand.getRule() instanceof TransformationRule
            && rel.getConvention() != previous.getConvention()) {
          continue;
        }
        if (!operand.matches(rel)) { //使用 operand.matches(rel) 检查后继节点是否符合当前操作数的要求
          continue;
        }
        //如果是递增模式并且当前操作数的 childPolicy 不是无序的，则进一步检查当前节点是否是前一个操作数的有效子节点
        if (ascending && operand.childPolicy != RelOptRuleOperandChildPolicy.UNORDERED) {
          // We know that the previous operand was *a* child of its parent,
          // but now check that it is the *correct* child.
          if (previousOperand.ordinalInParent >= rel.getInputs().size()) {
            continue;
          }
          final RelSubset input =
              (RelSubset) rel.getInput(previousOperand.ordinalInParent);
          if (previousOperand.getMatchedClass() == RelSubset.class) {
            // The matched subset (previous) should satisfy our input subset (input)
            if (input.getSubsetsSatisfyingThis().noneMatch(previous::equals)) {
              continue;
            }
          } else {
            if (!input.contains(previous)) {
              continue;
            }
          }
        }

        // Assign "childRels" if the operand is UNORDERED.
        switch (parentOperand.childPolicy) {
        case UNORDERED:
          // Note: below is ill-defined. Suppose there's a union with 3 inputs,
          // and the rule is written as Union.class, unordered(...)
          // What should be provided for the rest 2 arguments?
          // RelSubsets? Random relations from those subsets?
          // For now, Calcite code does not use getChildRels, so the bug is just waiting its day
          if (ascending) {
            final List<RelNode> inputs = Lists.newArrayList(rel.getInputs());
            inputs.set(previousOperand.ordinalInParent, previous);
            setChildRels(rel, inputs);
          } else {
            List<RelNode> inputs = getChildRels(previous);
            if (inputs == null) {
              inputs = Lists.newArrayList(previous.getInputs());
            }
            inputs.set(operand.ordinalInParent, rel);
            setChildRels(previous, inputs);
          }
          break;
        default:
          break;
        }

        rels[operandOrdinal] = rel;
        matchRecurse(solve + 1);
      }
    }
  }
}
